title: "AndrÃ© C. Santos"
author: "AndrÃ© C. Santos"
email: andresantos@dei.uc.pt
description: >
  *"You can't really imagine music* ğŸµ <br>
               *without technology* ğŸ’»*."* - Brian Eno
theme: minima  # ou o tema que escolheres
header_pages: 
- index.md
- publications.md
twitter_username: SantoAndre_6
github_username: asantos-6